[project]
name = "amol-thakkar-personal-site"
version = "0.1.0"
description = ""
authors = [
    {name = "Amol Thakkar"}
]
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "requests>=2.31.0",
]
